#!/bin/bash

# Generate Meson Cross-Compilation Files for iOS Targets
# Creates cross-files for both iOS device (ARM64) and simulator (ARM64)

set -e

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Validate Xcode installation
if ! xcode-select -p &> /dev/null; then
    log_error "Xcode Command Line Tools not found"
    log_error "Install with: xcode-select --install"
    exit 1
fi

XCODE_PATH=$(xcode-select -p)
log_info "Using Xcode at: $XCODE_PATH"

# Configuration
MIN_IOS_VERSION="${MIN_IOS_VERSION:-12.0}"
OUTPUT_DIR="${OUTPUT_DIR:-.}"

log_info "Minimum iOS version: $MIN_IOS_VERSION"
log_info "Output directory: $OUTPUT_DIR"

# SDK paths
IOS_DEVICE_SDK="$XCODE_PATH/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk"
IOS_SIMULATOR_SDK="$XCODE_PATH/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk"

# Validate SDK paths
if [ ! -d "$IOS_DEVICE_SDK" ]; then
    log_error "iOS Device SDK not found at: $IOS_DEVICE_SDK"
    exit 1
fi

if [ ! -d "$IOS_SIMULATOR_SDK" ]; then
    log_error "iOS Simulator SDK not found at: $IOS_SIMULATOR_SDK"
    exit 1
fi

log_info "✓ iOS Device SDK: $IOS_DEVICE_SDK"
log_info "✓ iOS Simulator SDK: $IOS_SIMULATOR_SDK"

# Find compiler binaries
CLANG=$(xcrun -f clang)
CLANGXX=$(xcrun -f clang++)
AR=$(xcrun -f ar)
STRIP=$(xcrun -f strip)
RANLIB=$(xcrun -f ranlib)

log_info "Compiler binaries:"
log_info "  clang: $CLANG"
log_info "  clang++: $CLANGXX"
log_info "  ar: $AR"
log_info "  strip: $STRIP"
log_info "  ranlib: $RANLIB"

# Generate iOS Device cross-file
log_info "Generating iOS Device cross-file..."
DEVICE_CROSS_FILE="$OUTPUT_DIR/ios-device-cross.txt"

cat > "$DEVICE_CROSS_FILE" << EOF
# Meson cross-compilation file for iOS Device (ARM64)
# Generated by generate-cross-file.sh

[binaries]
c = '$CLANG'
cpp = '$CLANGXX'
ar = '$AR'
strip = '$STRIP'
ranlib = '$RANLIB'
pkgconfig = 'pkg-config'

[properties]
sys_root = '$IOS_DEVICE_SDK'
c_args = ['-arch', 'arm64', '-mios-version-min=$MIN_IOS_VERSION', '-isysroot', '$IOS_DEVICE_SDK']
cpp_args = ['-arch', 'arm64', '-mios-version-min=$MIN_IOS_VERSION', '-isysroot', '$IOS_DEVICE_SDK']
c_link_args = ['-arch', 'arm64', '-mios-version-min=$MIN_IOS_VERSION', '-isysroot', '$IOS_DEVICE_SDK']
cpp_link_args = ['-arch', 'arm64', '-mios-version-min=$MIN_IOS_VERSION', '-isysroot', '$IOS_DEVICE_SDK']

[host_machine]
system = 'darwin'
cpu_family = 'aarch64'
cpu = 'arm64'
endian = 'little'

[built-in options]
default_library = 'static'
EOF

log_info "✓ Created: $DEVICE_CROSS_FILE"

# Generate iOS Simulator cross-file
log_info "Generating iOS Simulator cross-file..."
SIMULATOR_CROSS_FILE="$OUTPUT_DIR/ios-simulator-cross.txt"

cat > "$SIMULATOR_CROSS_FILE" << EOF
# Meson cross-compilation file for iOS Simulator (ARM64)
# Generated by generate-cross-file.sh

[binaries]
c = '$CLANG'
cpp = '$CLANGXX'
ar = '$AR'
strip = '$STRIP'
ranlib = '$RANLIB'
pkgconfig = 'pkg-config'

[properties]
sys_root = '$IOS_SIMULATOR_SDK'
c_args = ['-arch', 'arm64', '-mios-version-min=$MIN_IOS_VERSION', '-isysroot', '$IOS_SIMULATOR_SDK']
cpp_args = ['-arch', 'arm64', '-mios-version-min=$MIN_IOS_VERSION', '-isysroot', '$IOS_SIMULATOR_SDK']
c_link_args = ['-arch', 'arm64', '-mios-version-min=$MIN_IOS_VERSION', '-isysroot', '$IOS_SIMULATOR_SDK']
cpp_link_args = ['-arch', 'arm64', '-mios-version-min=$MIN_IOS_VERSION', '-isysroot', '$IOS_SIMULATOR_SDK']

[host_machine]
system = 'darwin'
cpu_family = 'aarch64'
cpu = 'arm64'
endian = 'little'

[built-in options]
default_library = 'static'
EOF

log_info "✓ Created: $SIMULATOR_CROSS_FILE"

echo ""
log_info "=========================================="
log_info "Cross-file generation completed successfully!"
log_info "=========================================="
log_info "Device cross-file: $DEVICE_CROSS_FILE"
log_info "Simulator cross-file: $SIMULATOR_CROSS_FILE"
log_info ""
log_info "Usage with Meson:"
log_info "  meson setup build --cross-file=$DEVICE_CROSS_FILE"
log_info "  meson setup build --cross-file=$SIMULATOR_CROSS_FILE"

exit 0
