#!/bin/sh
set -e

# Disable cast-function-type-strict warning for compatibility with older harfbuzz
CFLAGS="$CFLAGS -Wno-error=cast-function-type-strict"
CXXFLAGS="$CXXFLAGS -Wno-error=cast-function-type-strict"
export CFLAGS CXXFLAGS

$SRC/harfbuzz*/configure $COMMON_OPTIONS \
							--with-icu=no \
							--with-glib=no \
							--with-fontconfig=no \
							--with-coretext=no \
							--with-freetype=yes \
							--with-cairo=no
make install