#!/bin/sh
set -e

# Disable cast-function-type-strict warning for compatibility with older harfbuzz
export CFLAGS="$CFLAGS -Wno-cast-function-type-strict"
export CXXFLAGS="$CXXFLAGS -Wno-cast-function-type-strict"

$SRC/harfbuzz*/configure $COMMON_OPTIONS \
							--with-icu=no \
							--with-glib=no \
							--with-fontconfig=no \
							--with-coretext=no \
							--with-freetype=yes \
							--with-cairo=no
make install