#!/bin/sh
set -e

# 确保 configure 脚本有执行权限
chmod +x $SRC/libass*/configure 2>/dev/null || true

OPT="--disable-fontconfig \
	--disable-require-system-font-provider \
	--disable-directwrite \
	--enable-coretext"

$SRC/libass*/configure $COMMON_OPTIONS $OPT
							
make install